# Generated by Django 4.2.7 on 2023-11-09 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0002_classmate_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmate',
            name='address',
            field=models.CharField(default=datetime.datetime(2023, 11, 9, 22, 20, 7, 339621, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classmate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=datetime.datetime(2023, 11, 9, 22, 20, 28, 194303, tzinfo=datetime.timezone.utc), max_length=1),
            preserve_default=False,
        ),
    ]
