# Generated by Django 4.2.7 on 2023-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0003_classmate_address_classmate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
